version: 2
jobs:
  build:
    working_directory: ~/yaml-compare
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: pwd
          command: pwd && ls
      - run:
          name: install dependencies
          command: go get ./...
      - run:
          name: build project
          command: go build main/main.go
#      - store_artifacts:
#          path: build/libs/yaml-compare.jar
      # Persist the specified paths (workspace/echo-output) into the workspace for use in downstream job.
#      - persist_to_workspace:
#          root: ./build/libs/
#          # Must be relative path from root
#          paths:
#            - .

  publish-release:
    working_directory: ~/work
    docker:
      - image: circleci/golang:1.12
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${CIRCLE_BUILD_NUM} yaml-compare.jar
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - publish-release:
          context: yaml-compare
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /\d+\.\d+\.\d+$/
